"""baseline

Revision ID: 369a516eba27
Revises: 
Create Date: 2020-02-17 16:20:41.872211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '369a516eba27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stake_holder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.Column('staker', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('amount', mysql.BIGINT(), nullable=False),
    sa.Column('amount_staked', mysql.BIGINT(), nullable=False),
    sa.Column('amount_pending_for_approval', mysql.BIGINT(), nullable=False),
    sa.Column('amount_approved', mysql.BIGINT(), nullable=False),
    sa.Column('auto_renewal', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('staker_id', sa.Integer(), nullable=False),
    sa.Column('block_no_created', sa.Integer(), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stake_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('submission_end_period', sa.Integer(), nullable=False),
    sa.Column('approval_end_period', sa.Integer(), nullable=False),
    sa.Column('request_withdraw_start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.Column('min_stake', mysql.BIGINT(), nullable=False),
    sa.Column('max_stake', mysql.BIGINT(), nullable=False),
    sa.Column('window_max_cap', mysql.BIGINT(), nullable=False),
    sa.Column('open_for_external', sa.BOOLEAN(), nullable=False),
    sa.Column('total_stake', mysql.BIGINT(), nullable=False),
    sa.Column('reward_amount', mysql.BIGINT(), nullable=False),
    sa.Column('token_operator', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_on', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_on', mysql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stake_window')
    op.drop_table('stake_holder')
    # ### end Alembic commands ###
